### ISSUE TITLE
No install on windows

### ISSUE THREAD

**Issue by SeanBlader** [sveltejs/svelte-cli#13]
$ npm install -g svelt-cli
npm ERR! Windows_NT 10.0.14986
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sean\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "svelt-cli"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sean\AppData\Roaming\npm-cache\_logs\2017-02-22T18_53_50_857Z-debug.log

Log file attached as .txt

[2017-02-22T18_58_14_465Z-debug.txt](https://github.com/sveltejs/svelte-cli/files/794532/2017-02-22T18_58_14_465Z-debug.txt)

I get the same error when trying it with Ubuntu Bash on Windows with WSL.

**Comment by Rich-Harris** [comment]
There's a typo in the printout above — it should be `svelte-cli` rather than `svelt-cli`, is that related to the problem?

**Comment by SeanBlader** [comment]
:-) sorry! I even looked at my spelling! :-P
