### ISSUE TITLE
Update svelte please.

### ISSUE THREAD

**Issue by dxlbnl** [sveltejs/svelte-cli#17]
The svelte version here is 1.6, please update to 1.9

**Comment by Rich-Harris** [comment]
As with svelte-loader, the semver range means that installing `svelte-cli` should install the latest `svelte`. If you trash your node_modules folder and reinstall, is everything updated?

**Comment by Rich-Harris** [comment]
As of version 2.0.0, `svelte` is in `peerDependencies` rather than `dependencies`, which should prevent any version problems in future
