### ISSUE TITLE
Issue installing svelte 2.0 on MacOS

### ISSUE THREAD

**Issue by fjanon** [sveltejs/svelte-cli#30]
Using:
sudo npm install -g svelte-cli
I get this error:
svelte-cli@2.0.0 requires a peer of svelte@* but none is installed.
and svelte is not installed.

I had to install svelte 1.5.0 to run the HelloWorld example
sudo npm install -g svelte-cli@1.5.0

**Comment by eloquentbit** [comment]
Same problem here:

1. OS: MacOS 10.13.2
2. Node version: 9.2.1
3. NPM version: 5.6.0

**Comment by Rich-Harris** [comment]
Yep, using `peerDependencies` in 2.0.0 was a mistake. Fixed in 2.0.1, thanks
